# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

flags:
  unit:
    paths:
      - src/aetherlens/
    carryforward: true

  integration:
    paths:
      - src/aetherlens/
    carryforward: true

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "scripts/"
  - "docker/"
  - "docs/"
  - "migrations/"
  - "**/__pycache__"
  - "**/*.pyc"
  - "setup.py"
